-- Inserting Items into CGStudio
USE team3;

-- Inserting into product

-- RPG Games
INSERT INTO product VALUES (NULL, 2, 'RPG','PC','Assassin''s Creed III','images/assasinsCreed.jpg','Set in Colonial America, the Assassin-Templar war has become involved in the American Revolution. Through the series'' protagonist, Desmond Miles, the player controls his ancestor, a young, half-English, half-Mohawk man named Ratonhnhaké:ton, also known as Connor.',59.99, 1, NOW(), NOW());
INSERT INTO product VALUES (NULL, 6, 'RPG','PC','The Elder Scrolls V: Skyrim','images/skyrim.jpg','Following the Dragon attack on Helgen, the player character may choose to escape either with Hadvar, an Imperial soldier, or Ralof, a Stormcloak rebel. After the escape, the player travels to the town of Riverwood. The player is asked to journey to the city of Whiterun, and request aid from the Jarl against the Dragon threat. The Jarl agrees to send soldiers to Riverwood, but asks that the player retrieve a Dragonstone.',59.99, 1, NOW(), NOW());
INSERT INTO product VALUES (NULL, 13, 'RPG','PC','World of Warcraft','images/wow.jpg','As characters become more developed, they gain various talents and skills, requiring the player to further define the abilities of that character. Characters can choose from a variety of professions, such as tailoring, blacksmithing, or mining. Characters can learn four secondary skills: archeology, cooking, fishing, and first-aid. Characters may form and join guilds, allowing characters within the guild access to the guild''s chat channel, the guild name and optionally allowing other features, including a guild tabard, guild bank, and dues.',59.99, 1, NOW(), NOW());
INSERT INTO product VALUES (NULL, 11, 'RPG','Wii','The Legend of Zelda: Skyward Sword','images/zelda.jpg','In the series'' chronology, Skyward Sword is officially the earliest point in the Zelda timeline, and elaborates on the origins of the Master Sword and Ganon. According to legend, after the creation of the land that would later become Hyrule, the Triforce was entrusted by the Golden Goddesses Din, Farore and Nayru to the goddess known as Hylia. However, the Demon King Demise gathered an army to take the Triforce for his own evil intent.',59.99, 1, NOW(), NOW());
INSERT INTO product VALUES (NULL, 9, 'RPG','PC','Diablo III','images/d3.jpg','The game takes place in Sanctuary, the dark fantasy world of the Diablo series, twenty years after the events of Diablo II. Deckard Cain and his niece Leah are in the Tristram Cathedral investigating ancient texts regarding an ominous prophecy. Suddenly, a mysterious star falling from the sky strikes the Cathedral, creating a deep crater into which Deckard Cain disappears.',59.99, 1, NOW(), NOW());

-- Puzzle Games
INSERT INTO product VALUES (NULL, 23, 'Puzzle','Xbox','Tetris Splash','images/tetris.jpg','Big Brain Academy: Wii Degree includes a single player mode whereby the player uses a brain to effectively answer questions correctly. The game also includes a multiplayer mode, where the player can competitively train against other players. Big Brain Academy: Wii Degree makes use of the Wii Remote, allowing the player to point and click on-screen.',5.99, 0, NOW(), NOW());
INSERT INTO product VALUES (NULL, 2, 'Puzzle','Xbox','Portal 2','images/portal2.jpg','Portal 2 is a puzzle game presented from the first-person perspective. Players act as Chell in the single-player campaign, as one of two robots, Atlas and P-Body, in the co-operative campaign, or as a simplistic humanoid icon for community-developed puzzles. All four can move, look, and interact with the environment.',29.99, 0, NOW(), NOW());

-- Racing Games
INSERT INTO product VALUES (NULL, 10, 'Racing','PS3','Need for Speed: Most Wanted','images/needForSpeed.jpg','Most Wanted allows players to select one car and compete against other racers to reach a destination. Cops are integrated into certain racing sessions, in which the police deploy vehicles and tactics to stop the player''s car and arrest the player, like the original Most Wanted.',59.99, 1, NOW(), NOW());
INSERT INTO product VALUES (NULL, 9, 'Racing','Xbox','Forza Motorsport 4','images/forza.jpg','Forza Motorsport 4 is racing video game, and the fourth in the Forza Motorsport series. Like Sony''s Gran Turismo franchise, Forza games are racing simulations; heavy emphasis is placed on making the cars drive and look as realistic as possible. Races are conducted on closed circuit tracks.',39.99, 0, NOW(), NOW());
INSERT INTO product VALUES (NULL, 4, 'Racing','Xbox','Mario Kart Wii','images/mariokart.jpg','Mario Kart Wii is a racing video game where the player races in each of the 32 different tracks, including 16 new tracks, and 16 "retro" tracks from previous Mario Kart games; 4 each from Mario Kart 64, Mario Kart: Double Dash!! and Mario Kart DS, and two each from Super Mario Kart and Mario Kart: Super Circuit, and up to twelve characters can participate in a race instead of the traditional eight.',24.99, 1, NOW(), NOW());

-- FPS Games
INSERT INTO product VALUES (NULL, 23, 'FPS','PC','Left for Dead 2','images/left4dead.jpg','In the year 2025, a Special Forces unit led by David Mason arrive at "The Vault", a secret location that is home to the aged Frank Woods, who they believe has information on the whereabouts of Raul Menendez. Woods admits that Menendez had visited him, and gives Mason a locket that Menendez had left behind.',19.99, 0, NOW(), NOW());
INSERT INTO product VALUES (NULL, 6, 'FPS','PS3','Call of Duty: Black Ops II','images/callOfDuty.jpg','In the year 2025, a Special Forces unit led by David Mason arrive at "The Vault", a secret location that is home to the aged Frank Woods, who they believe has information on the whereabouts of Raul Menendez. Woods admits that Menendez had visited him, and gives Mason a locket that Menendez had left behind.',49.99, 1, NOW(), NOW());
INSERT INTO product VALUES (NULL, 14, 'FPS','Xbox','Halo 4','images/halo4.jpg','Like its predecessor, Left 4 Dead is set shortly after a worldwide pandemic of an infectious disease that rapidly transforms humans into zombie-like creatures and mutated forms that demonstrate extreme aggression towards non-infected (much like the infected in 28 Days Later).',44.99, 1, NOW(), NOW());

-- Sport Games
INSERT INTO product VALUES (NULL, 3, 'Sport','Xbox','NHL 13','images/nhl.jpg','NHL 13 is an ice hockey video game developed by EA Canada published by EA Sports. It is the 22nd installment of the NHL series and was released between September 11–13, 2012, in North America, Europe as well as Australia and New Zealand.',39.99, 1, NOW(), NOW());
INSERT INTO product VALUES (NULL, 11, 'Sport','PS3','NBA 2K13','images/nba.jpg','Like its predecessors, NBA 2K13 simulates NBA basketball games. One of the game''s new control features allocates dribbling to the right analog stick on the controller, much like EA''s NBA Live series.',34.99, 0, NOW(), NOW());
INSERT INTO product VALUES (NULL, 2, 'Sport','Wii','Mario Power Tennis','images/marioTennis.jpg','Mario Power Tennis features variations of tennis matches consisting of characters, courts, and scenarios based on the Mario series.',14.99, 0, NOW(), NOW());

-- Strategy Games
INSERT INTO product VALUES (NULL, 3, 'Strategy','PC','StarCraft II: Wings of Liberty','images/starcraft.jpg','Four years after the Brood War, the Dominion is once again the dominant Terran power in the Koprulu sector. News reports reveal that in the four years since the end of the Brood Wars the standing Dominion military forces have been reduced and trillions have been spent hunting down rebel forces that operate against the Dominion.',59.99, 1, NOW(), NOW());
INSERT INTO product VALUES (NULL, 5, 'Strategy','PC','Sid Meier''s Civilization V','images/civilization.jpg','Civilization V is a turn-based strategy game, where each player represents the leader of a certain nation or ethnic group ("civilization") and must guide its growth over the course of thousands of years.',34.99, 1, NOW(), NOW());

-- Platform Games
INSERT INTO product VALUES (NULL, 2, 'Platform','Wii','Super Mario Galaxy 2','images/mario.jpg','The gameplay of Super Mario Galaxy 2 is similar to Super Mario Galaxy, with a focus on platforming based on and around 3D planets (referred to collectively as galaxies) with varying themes, sizes, landscapes, and climates.',39.99, 0, NOW(), NOW());
INSERT INTO product VALUES (NULL, 12, 'Platform','PS3','Ratchet & Clank: All 4 One','images/rachet&clank.jpg','The game begins when Galactic President Captain Qwark goes to the city of Luminopolis to receive an "Intergalactic Tool of Justice Award", and he asks Ratchet and Clank to escort him. When the ceremony begins, Dr. Nefarious arrives and awakens a light-eating Z''Grute from cyrosleep, but it immediately turns against him, forcing Dr. Nefarious to join Ratchet, Clank and Qwark to stop it.',39.99, 0, NOW(), NOW());

-- Fighting Games
INSERT INTO product VALUES (NULL, 11, 'Fighting','Xbox','Mortal Kombat 9','images/mortalkombat.jpg','Following the events of Mortal Kombat: Armageddon, both the forces of light and darkness have been wiped out, with only the thunder god Raiden and Shao Kahn remaining to represent their parties. A severely weakened Raiden is about to be killed by Shao Kahn, but casts a last-minute spell on his now shattered magical amulet, directing it to contact his past self with the vague message "He must win".',19.99, 1, NOW(), NOW());
INSERT INTO product VALUES (NULL, 7, 'Fighting','Wii','Super Smash Bros. Brawl','images/superSmash.jpg','Following its predecessors, Brawl uses a battle system unlike that of typical fighting games. Players can choose from a large selection of characters, each attempting to knock their opponents off the screen as they fight on various stages.',24.99, 1, NOW(), NOW());
INSERT INTO product VALUES (NULL, 3, 'Fighting','Xbox','Street Fighter IV','images/streetFighter.jpg','Street Fighter IV takes place several months after the events of Street Fighter II (thus is chronologically set between Street Fighter II and III). After M.Bison''s survival from his encounter with Akuma, the S.I.N. corporation began another fighting tournament in order to draw out the most powerful fighters on Earth to complete the BLECE project.',29.99, 1, NOW(), NOW());

-- Indie Games
INSERT INTO product VALUES (NULL, 3, 'Indie','PC','Minecraft','images/minecraft.jpg','Minecraft is an open world game that has no specific goals for the player to accomplish, allowing players a large amount of freedom in choosing how to play the game. However, there is an optional achievement system. The gameplay by default is first person, but players have the option to play in third person mode. The core gameplay revolves around breaking and placing blocks.',24.99, 0, NOW(), NOW());
INSERT INTO product VALUES (NULL, 12, 'Indie','Xbox','Fez','images/fez.jpg','The plot of Fez revolves around Gomez, a two-dimensional creature who lives in a flat, 2D world. One day, Gomez encounters a strange and mysterious artifact called the Hexahedron, which gives him a magical fez hat that allows him to perceive a third dimension.',19.99, 1, NOW(), NOW());
INSERT INTO product VALUES (NULL, 34, 'Indie','PC','Democracy','images/democracy2.jpg','After deciding which nation to play as, the player must win the support of various factions which make up the electorate, including the religious, patriots, parents, capitalists, socialists, liberals, conservatives and others, and thus win the ensuing elections that take place.',9.99, 0, NOW(), NOW());

-- Educational
INSERT INTO product VALUES (NULL, 15, 'Educational','Wii','Cars 2','images/cars.jpg','Cars 2 is a third person racing game where players have a choice of 25 different characters, and will train to become a world-class spy.',29.99, 1, NOW(), NOW());
INSERT INTO product VALUES (NULL, 2, 'Educational','Wii','Brain Age','images/brainAge.jpg','The game consists of many minigames which help you improve your brain capacity.',19.99, 1, NOW(), NOW());
INSERT INTO product VALUES (NULL, 4, 'Educational','Wii','Art Academy','images/artAcademy.jpg','Kinect Sesame Street TV is an interactive television program for the Xbox 360 video game console. It is based on the Sesame Street franchise and is aimed at children. Because of its motion gesture features, the game requires the Kinect peripheral.',34.99, 1, NOW(), NOW());
